### ISSUE TITLE
Can I use it as an api in python

### ISSUE THREAD

**Issue by Ahmedniz1** [Wildric-Auric/MidJourney-Wrapper#33]
Hi, I want to use midjourney in my web application, can I use this wrapper to use mid journey in python, without calling anything over discord.

**Comment by Wildric-Auric** [comment]
No, there is no way to communicate with MidJourney servers without discord.

**Comment by Ahmedniz1** [comment]
can you sum up what this repo does?
I felt by using this wrapper, I can somehow get midjourney generated results in python.

**Comment by Wildric-Auric** [comment]
Although it should be updated since some commands have changed for MidJourney bot, I think  the description in the [Readme](https://github.com/Wildric-Auric/MidJourney-Wrapper/blob/main/README.md) contains everything you need to know. It is obligatory to have a server with different bots, then you can just get the image through discord API and do whatever you want with it.

**Comment by btcmonkey945** [comment]
> Hi, I want to use midjourney in my web application, can I use this wrapper to use mid journey in python, without calling anything over discord.

Hi, have you found any solution for such purpose? Appreciated.
