### ISSUE TITLE
Another interaction way for UV and refresh

### ISSUE THREAD

**Issue by kuyin** [Wildric-Auric/MidJourney-Wrapper#6]
some advice which I'm using right now is creating my own button message and store the information of uv and refresh 
for interaction. this can avoid the issue when two or more people modify the $value at the same time.
![E9746640-596D-4A5A-BF61-CE7E1C4E0032](https://user-images.githubusercontent.com/7321275/200210651-abd00bda-dae4-4169-bc67-35197ba31c6e.png)

**Comment by Wildric-Auric** [comment]
Hey, sorry for late response. Yeah sure that's a good idea. You will just need to store the targetted message id and url hash in your message containing the buttons, since you will need that information for upscaling and making variations. Now that the other problem is solved, feel free to open a button branch if that pleases you!

**Comment by mjh1b** [comment]
@kuyin @Wildric-Auric is it possible to create a custom response message? As in instead of the Midjourney bot given a response back it is the mj_imagine bot that gives the response back with a custom message. So like just how MidJourney bot gives back the message but with custom buttoms below (so that it can effectively do mj_target + the relevant upscale/downscale in one button click?) 

Thank you!

**Comment by Wildric-Auric** [comment]
In case you want custom message without the midjourney message you can delete this latter one but I don't think that would work. I would suggest then making midjourney post it's message in a private channel (not accessed by members) and you would then use that messages to publish images, choice's buttons etc in a public channel.

**Comment by RomainC-lab** [comment]
Hello @Wildric-Auric and @mjh1b,
I have created a pull request for this here: #12.
Unfortunately, it is not possible, if you remove the original midjourney message, you will not be able to do some actions after.

**Comment by Wildric-Auric** [comment]
A new branch containing @RomainC-lab changes has been added.
